FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\GUI\\GUIElement.bf", "src\\Math\\Vector2.bf", "src\\Program.bf", "Disassembly", "Disassembly", "Disassembly", "Disassembly"]

[MainWindow]
X = 1670
Y = 317
Width = 1458
Height = 1771
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 488.0
RequestedHeight = 246.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 112.0
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 422.0
RequestedHeight = 572.0
SizePriority = 422.0
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 3347.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "GUIElement.bf"
TabWidth = 120.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\GUI\\GUIElement.bf"
CursorPos = 663
ProjectName = "Voxis"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Vector2.bf"
TabWidth = 96.66666
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Math\\Vector2.bf"
CursorPos = 9311
VertPos = 6486.0
ProjectName = "Voxis"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 102.6667
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 58
ProjectName = "Voxis"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 422.0
RequestedHeight = 481.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 422.0
RequestedHeight = 422.0
SizePriority = 0.5738984
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 97.33334
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 85.33334
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 194.0}, {Width = 194.0}, {Width = 194.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = "MaterialInstanceProperties"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 76.66666
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 550.0}, {Width = 1011.0}, {Width = 194.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Profile"
TabWidth = 86.66666
TabIsPinned = false
Type = "ProfilePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Errors"
TabWidth = 83.33334
TabIsPinned = false
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 422.0
RequestedHeight = 422.0
SizePriority = 0.4261016
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 116.6667
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 94.66666
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 104.0
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 109.3333
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 89.33334
TabIsPinned = false
Type = "OutputPanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
