FileVersion = 1

[Project]
Name = "Voxis"
StartupObject = "Voxis.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/debug/x64/glfw3dll.lib", "$(ProjectDir)/dist/debug/x64/STBLib.lib", "$(ProjectDir)/dist/debug/x64/sokol.lib"]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/dist/debug/x64/*.dll\", \"$(TargetDir)/\")", "CopyFilesIfNewer(\"$(ProjectDir)/assets/*\", \"$(TargetDir)/assets/\")"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)/dist/debug/x64/glfw3dll.lib", "$(ProjectDir)/dist/debug/x64/STBLib.lib", "$(ProjectDir)/dist/debug/x64/sokol.lib"]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/dist/debug/x64/*.dll\", \"$(TargetDir)/\")", "CopyFilesIfNewer(\"$(ProjectDir)/assets/*\", \"$(TargetDir)/assets/\")"]
